cc_test(
  name = "dfmt_test",
  srcs = ["dfmt_test.cc"],
  deps = [
    "//doubleback:dfmt",
    "//third_party/gtest",
  ],
)

cc_binary(
  name = "dfmt_echo",
  srcs = ["dfmt_echo.c"],
  deps = [
    "//doubleback:dfmt",
    "//doubleback:dparse",
  ],
)
