cc_test(
  name = "d2s_table_test",
  srcs = ["d2s_table_test.cc"],
  deps = [
    "//ryu",
    "//third_party/gtest",
  ],
)

cc_test(
  name = "dfmt_test",
  srcs = ["dfmt_test.cc"],
  deps = [
    "//ryu",
    "//third_party/gtest",
  ],
)

cc_binary(
  name = "dfmt_echo",
  srcs = ["dfmt_echo.c"],
  deps = [
    "//ryu",
    "//ryu:ryu_parse",
  ],
)
